<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NextWeb.DocumentPlatform.Engine\NextWeb.DocumentPlatform.Engine.csproj" />
    <ProjectReference Include="..\NextWeb.DocumentPlatform.Domain\NextWeb.DocumentPlatform.Domain.csproj" />
    <ProjectReference Include="..\NextWeb.DocumentPlatform.Application\NextWeb.DocumentPlatform.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
